# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openunipay', '0002_remove_alipayorder_interface_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5bf9\u624b\u65b9\u7528\u6237\u6807\u8bc6'),
        ),
    ]
